[package]
name = "rust-actix-web-author-book-management-system"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
sea-orm = { version = "0.12", features = ["sqlx-mysql", "sqlx-postgres", "runtime-actix-native-tls"] }
sea-orm-migration = "0.12"
tokio = { version = "1", features = ["full"] }
openssl = "0.10"
